/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import fonts.Fuentes;
import javax.swing.JButton;
import javax.swing.SwingConstants;

/**
 *
 * @author Paola Mejia
 */
public class Comic extends javax.swing.JPanel {

    /**
     * Creates new form Comic
     */
    Fuentes tipoFuentes;
    public Comic() {

        initComponents();
       EstadoLabel();
       fontDesign();
    }
    
    
     private void fontDesign()
    {      
        tipoFuentes = new Fuentes();
       // jLabel1.setFont(tipoFuentes.fuente(tipoFuentes.DMSans, 0, 35));
        img1.setHorizontalAlignment(SwingConstants.CENTER);

       
        btnSiguiente.setText("<html><font color='white'> Siguiente </font></html>");
        caracBtn(btnSiguiente);
    }
        
    
    private void caracBtn(JButton btn)
    {
        btn.setFont((tipoFuentes.fuente(tipoFuentes.KoHoRegular, 0, 40)));
        btn.setHorizontalTextPosition(JButton.CENTER);
        btn.setVerticalTextPosition(JButton.CENTER);
        btn.setVerticalAlignment(JButton.CENTER);
        btn.setHorizontalAlignment(JButton.CENTER); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        img5 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1296, 624));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_img/KoaRBtn2.png"))); // NOI18N
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 500, 250, 90));

        img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgcomic/newpackage/5 1.png"))); // NOI18N
        jPanel1.add(img5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 1060, -1));

        img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgcomic/newpackage/4 1.png"))); // NOI18N
        jPanel1.add(img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 900, 280));

        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgcomic/newpackage/3 (1) 1.png"))); // NOI18N
        jPanel1.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, 280, 1070, 360));

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgcomic/newpackage/2 (1) 1.png"))); // NOI18N
        jPanel1.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -20, 1070, 370));

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgcomic/newpackage/2 9.png"))); // NOI18N
        jPanel1.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    
    public JButton getBtnSiguiente()
    {
        return btnSiguiente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables



public void EstadoLabel()
{
    img1.setVisible(false);
    img2.setVisible(false);
    img3.setVisible(false);
    img4.setVisible(false);
    img5.setVisible(false);
    btnSiguiente.setVisible(false);
   iniciarThread1();
    
}


public void iniciarThread1()
{
   Thread jumpThread = new Thread(new Runnable() {
            @Override
            public void run() {
                 try {
            Thread.sleep(2500); // Pausa de 1.5 segundos
       } catch (InterruptedException e) {
                e.printStackTrace();
       }  
              img1.setVisible(true);
     try {
            Thread.sleep(1500); // Pausa de 1.5 segundos
       } catch (InterruptedException e) {
                e.printStackTrace();
       }  
      img2.setVisible(true);
        try {
            Thread.sleep(1500); // Pausa de 1.5 segundos
       } catch (InterruptedException e) {
                e.printStackTrace();
       }  
     img3.setVisible(true);
     
        try {
            Thread.sleep(1500); // Pausa de 1.5 segundos
       } catch (InterruptedException e) {
                e.printStackTrace();
       }  
     img4.setVisible(true);
     
     try {
            Thread.sleep(1500); // Pausa de 1.5 segundos
       } catch (InterruptedException e) {
                e.printStackTrace();
       }  
     img5.setVisible(true);
       btnSiguiente.setVisible(true);
       
 }});
jumpThread.start();
}
}