/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import fonts.Fuentes;
import javax.swing.JButton;
import javax.swing.SwingConstants;

/**
 *
 * @author Paola Mejia
 */
public class MapaNiveles extends javax.swing.JPanel {

    /**
     * Creates new form MapaNiveles
     */
    Fuentes tipoFuentes;
    public MapaNiveles() {
        initComponents();
        fontDesign();
    }

     private void fontDesign()
    {      
        tipoFuentes = new Fuentes();
       // jLabel1.setFont(tipoFuentes.fuente(tipoFuentes.DMSans, 0, 35));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);

       
        btnNvl1.setText("<html><font color='white'> Nivel 1 </font></html>");
        caracBtn(btnNvl1);
        
        btnNvl2.setText("<html><font color='white'> Nivel 2 </font></html>");
        caracBtn(btnNvl2);
        
        btnNvl3.setText("<html><font color='white'> Nivel 3 </font></html>");
        caracBtn(btnNvl3);
        
        btnNvl4.setText("<html><font color='white'> Nivel 4 </font></html>");
        caracBtn(btnNvl4);
        
        btnNvl5.setText("<html><font color='white'> Nivel 5 </font></html>");
        caracBtn(btnNvl5);
        
        btnNvl6.setText("<html><font color='white'> Nivel 6 </font></html>");
        caracBtn(btnNvl6);
    }
    
    private void caracBtn(JButton btn)
    {
        btn.setFont((tipoFuentes.fuente(tipoFuentes.KoHoRegular, 0, 20)));
        btn.setHorizontalTextPosition(JButton.CENTER);
        btn.setVerticalTextPosition(JButton.CENTER);
        btn.setVerticalAlignment(JButton.CENTER);
        btn.setHorizontalAlignment(JButton.CENTER); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNvl1 = new javax.swing.JButton();
        btnNvl2 = new javax.swing.JButton();
        btnNvl3 = new javax.swing.JButton();
        btnNvl4 = new javax.swing.JButton();
        btnNvl5 = new javax.swing.JButton();
        btnNvl6 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(147, 216, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MAPA DE NIVELES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        btnNvl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_img/KoaRbtn1Rounded.png"))); // NOI18N
        btnNvl1.setBorderPainted(false);
        btnNvl1.setContentAreaFilled(false);
        btnNvl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNvl1MouseClicked(evt);
            }
        });
        jPanel1.add(btnNvl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 130, 130));

        btnNvl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_img/KoaRbtn1Rounded.png"))); // NOI18N
        btnNvl2.setBorderPainted(false);
        btnNvl2.setContentAreaFilled(false);
        btnNvl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNvl2MouseClicked(evt);
            }
        });
        jPanel1.add(btnNvl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 130, 130));

        btnNvl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_img/KoaRbtn1Rounded.png"))); // NOI18N
        btnNvl3.setBorderPainted(false);
        btnNvl3.setContentAreaFilled(false);
        btnNvl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNvl3MouseClicked(evt);
            }
        });
        jPanel1.add(btnNvl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 130, 130));

        btnNvl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_img/KoaRbtn1Rounded.png"))); // NOI18N
        btnNvl4.setBorderPainted(false);
        btnNvl4.setContentAreaFilled(false);
        btnNvl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNvl4MouseClicked(evt);
            }
        });
        jPanel1.add(btnNvl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 130, 130));

        btnNvl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_img/KoaRbtn1Rounded.png"))); // NOI18N
        btnNvl5.setBorderPainted(false);
        btnNvl5.setContentAreaFilled(false);
        btnNvl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNvl5MouseClicked(evt);
            }
        });
        jPanel1.add(btnNvl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 130, 130));

        btnNvl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_img/KoaRbtn1Rounded.png"))); // NOI18N
        btnNvl6.setBorderPainted(false);
        btnNvl6.setContentAreaFilled(false);
        btnNvl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNvl6MouseClicked(evt);
            }
        });
        jPanel1.add(btnNvl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 130, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNvl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNvl6MouseClicked

    }//GEN-LAST:event_btnNvl6MouseClicked

    private void btnNvl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNvl1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNvl1MouseClicked

    private void btnNvl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNvl2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNvl2MouseClicked

    private void btnNvl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNvl3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNvl3MouseClicked

    private void btnNvl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNvl4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNvl4MouseClicked

    private void btnNvl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNvl5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNvl5MouseClicked

    public JButton getBtnNvl1()
    {
        return btnNvl1;
    }
    
    public JButton getBtnNvl2()
    {
        return btnNvl2;
    }
    
    public JButton getBtnNvl3()
    {
        return btnNvl3;
    }
    
    public JButton getBtnNvl4()
    {
        return btnNvl4;
    }

    public JButton getBtnNvl5()
    {
        return btnNvl5;
    }
    
    public JButton getBtnNvl6()
    {
        return btnNvl6;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNvl1;
    private javax.swing.JButton btnNvl2;
    private javax.swing.JButton btnNvl3;
    private javax.swing.JButton btnNvl4;
    private javax.swing.JButton btnNvl5;
    private javax.swing.JButton btnNvl6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
